### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/purple-libnotify-plus#13]
Seems that 1.99.2 was tagged in 2012. Any plans for a new tag?

**Comment by sardemff7** [comment]
Just pushed v2.99.2 as ab282b205dd5e6ff32f93772c11b36c1b7efeac3.

Tarballs are available at http://download.tuxfamily.org/purpleevents/purple-libnotify-plus/ as explained [there](http://purple-libnotify-plus.sardemff7.net/).
Do not forget to install [purple-events](http://purple-events.sardemff7.net/) too.

Thanks for using purple-libnotify+, and please report back any bug.

**Comment by mathstuf** [comment]
Thanks! I'm looking at getting it packaged for Fedora as well since this is one works with finch.
