### ISSUE TITLE
Installation Instruction

### ISSUE THREAD

**Issue by famfop** [sardemff7/purple-libnotify-plus#18]
I am trying to install your package but I'm not sure how to install the software. Can you maybe write a (very) short installation instruction? Thanks

**Comment by MartinConsultingServicesInc** [comment]
I did:

1. git clone https://github.com/sardemff7/purple-libnotify-plus
2. cd purple-libnotify-plus
3. ./autogen.sh        # Not sure if this is necessary
4. ./configure
5. make
6. make install

If you get an error about libnotify missing at step 4, it means you need the libnotify development package (libnotify-dev in Ubuntu).  Just install that and rerun ./configure.

**Comment by plasmoduck** [comment]
Im trying to build purple-libnotify-plus and I keep getting this:

configure: error: Package requirements (purple-events >= 0.99.1) were not met:

Package 'purple-events', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
